---
title: "Assignment #7"
author: "Ningqiao Li"
date: "March 30th"
output: html_notebook
---

*This is nice work!*

```{r include=FALSE}
library(here)
```


### Function creaton
```{r}
my_function <- function(x, y, p) {
  result_reg <- lm(y ~ x)
  result_res <- resid(result_reg)
  result_res2 <- sort(abs(result_res), decreasing = TRUE)
  ifelse (abs(result_res) >= result_res2[p], "TRUE", "FALSE")
}

```


***

### Scatterplot
```{r}
library(here)
my_data <- read.csv(here("Data", "Data for HW7.csv"))
p <- nrow(my_data)*0.1
residuals <- my_function(my_data$X, my_data$Y, p)
residuals
scatter_plot <- plot(my_data$X ~ my_data$Y,
                   main = "Regression for Assignment#7", 
                   xlab = "Explanatory variable", ylab="Response variable",
                   col = ifelse(residuals,"red","black"))
abline(lm(my_data$Y ~ my_data$X, data = my_data), col = "red")
```

***

### The second solution, using for loop, why doesn't it work?

*Because you first need to have a vector of logicals called "outcome" before*
*you can start assigning logicals to the slots of the vector.*

```{r}
my_function <- function(x, y, p) {
  result_reg <- lm(y ~ x)
  result_res <- resid(result_reg)
  result_res2 <- sort(abs(result_res), decreasing = TRUE)
  for (i in 1: length(result_res)) {
      if (abs(result_res[i]) >= result_res2[p]) {
    outcome[i] <- "TRUE"
    } else {
      outcome[i] <- "FALSE"
    }
    return (outcome[i])
  }
}


library(here)
my_data <- read.csv(here("Data", "Data for HW7.csv"))
p <- nrow(my_data)*0.1
residuals <- my_function(my_data$X, my_data$Y, p)
residuals
scatter_plot <- plot(my_data$X ~ my_data$Y,
                   main = "Regression for Assignment#7", 
                   xlab = "Explanatory variable", ylab="Response variable",
                   col = ifelse(residuals,"red","black"))
abline(lm(my_data$Y ~ my_data$X, data = my_data), col = "red")

```

